[2021-12-14 17:49:42,605] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-12-13T00:00:00+00:00 [queued]>
[2021-12-14 17:49:42,618] {taskinstance.py:876} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available 2021-12-13T00:00:00+00:00 [queued]>
[2021-12-14 17:49:42,618] {taskinstance.py:1067} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 17:49:42,618] {taskinstance.py:1068} INFO - Starting attempt 1 of 1
[2021-12-14 17:49:42,618] {taskinstance.py:1069} INFO - 
--------------------------------------------------------------------------------
[2021-12-14 17:49:42,654] {taskinstance.py:1087} INFO - Executing <Task(HttpSensor): is_api_available> on 2021-12-13T00:00:00+00:00
[2021-12-14 17:49:42,658] {standard_task_runner.py:52} INFO - Started process 22548 to run task
[2021-12-14 17:49:42,673] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'is_api_available', '2021-12-13T00:00:00+00:00', '--job-id', '5', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_precessing.py', '--cfg-path', '/tmp/tmprct446u6', '--error-file', '/tmp/tmpaobg_e7z']
[2021-12-14 17:49:42,674] {standard_task_runner.py:77} INFO - Job 5: Subtask is_api_available
[2021-12-14 17:49:42,750] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.is_api_available 2021-12-13T00:00:00+00:00 [running]> on host airflowvm
[2021-12-14 17:49:42,889] {taskinstance.py:1280} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2021-12-13T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-13T00:00:00+00:00
[2021-12-14 17:49:42,889] {http.py:101} INFO - Poking: api/
[2021-12-14 17:49:42,893] {base.py:69} INFO - Using connection to: id: user_api. Host: http://randomuser.me, Port: None, Schema: , Login: , Password: None, extra: {}
[2021-12-14 17:49:42,894] {http.py:140} INFO - Sending 'GET' to url: http://randomuser.me/api/
[2021-12-14 17:49:43,356] {base.py:243} INFO - Success criteria met. Exiting.
[2021-12-14 17:49:43,362] {taskinstance.py:1184} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20211213T000000, start_date=20211214T174942, end_date=20211214T174943
[2021-12-14 17:49:43,413] {taskinstance.py:1245} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-12-14 17:49:43,439] {local_task_job.py:151} INFO - Task exited with return code 0
